### ISSUE TITLE
about sampling in aleatoric tasks

### ISSUE THREAD

**Issue by Adamli12** [ShellingFord221/My-implementation-of-What-Uncertainties-Do-We-Need-in-Bayesian-Deep-Learning-for-Computer-Vision#1]
My understanding is that it is drawn from independent gaussian distributions of each class, since(you have also noticed), a diagonal matrix with one element for each logit value. Its a diagonal matrix therefore there is no covariance, so there is no need to draw from multi-variate distribution.

Thank you very much for your implementation.

**Comment by ShellingFord221** [comment]
So you mean that we can draw the logit vector separately from multiple univariate Gaussian distributions, rather than a multi-variate distribution with diagonal matrix? Somehow I think they are quite similar...

**Comment by Adamli12** [comment]
I wanted to answer your question in the paragraph begins with "Besides," in your README.md. But you seem to have already figured it out. You are right. Drawing then separately has the exact same effect as drawing from the diagonal matrix multi-variate distribution.
